-- Data Migration Dump

-- Users
INSERT INTO users (id, name, email, password, type, created_at, notes) VALUES (1767130333682, 'tensor', 'tensor@gmail.com', '$2b$10$ij./JsjUr4Hqw56v3wFwUusCad26sOI/6GRS8XowlFGkds0Uq/9Ci', 'student', '2025-12-30T21:32:13.682Z', NULL);

-- Lessons
INSERT INTO lessons (id, user_id, student_name, student_email, student_phone, student_country_code, subject, custom_subject, duration, status, price, datetime, notes, language, created_at) VALUES ('LESSON-1766830572032', 1766757085889, 'Jane Doe', 'jane@example.com', NULL, 'US', 'calculus', NULL, 60, 'new', 50, '2026-01-01T10:00', NULL, 'en', '2025-12-27T10:16:12.036Z');
INSERT INTO lessons (id, user_id, student_name, student_email, student_phone, student_country_code, subject, custom_subject, duration, status, price, datetime, notes, language, created_at) VALUES ('LESSON-1766830819017', 1766757085889, 'Bashar Mawase', 'basharmawaseru@gmail.com', '0533618622', NULL, 'algebra', NULL, 60, 'new', 50, '2025-12-28T12:30', NULL, 'ar', '2025-12-27T10:20:19.017Z');
INSERT INTO lessons (id, user_id, student_name, student_email, student_phone, student_country_code, subject, custom_subject, duration, status, price, datetime, notes, language, created_at) VALUES ('LESSON-1766830820678', 1766757085889, 'Bashar Mawase', 'basharmawaseru@gmail.com', '0533618622', NULL, 'algebra', NULL, 60, 'new', 50, '2025-12-28T12:30', NULL, 'ar', '2025-12-27T10:20:20.679Z');
INSERT INTO lessons (id, user_id, student_name, student_email, student_phone, student_country_code, subject, custom_subject, duration, status, price, datetime, notes, language, created_at) VALUES ('LESSON-1766830821460', 1766757085889, 'Bashar Mawase', 'basharmawaseru@gmail.com', '0533618622', NULL, 'algebra', NULL, 60, 'new', 50, '2025-12-28T12:30', NULL, 'ar', '2025-12-27T10:20:21.460Z');
INSERT INTO lessons (id, user_id, student_name, student_email, student_phone, student_country_code, subject, custom_subject, duration, status, price, datetime, notes, language, created_at) VALUES ('LESSON-1766830822245', 1766757085889, 'Bashar Mawase', 'basharmawaseru@gmail.com', '0533618622', NULL, 'algebra', NULL, 60, 'new', 50, '2025-12-28T12:30', NULL, 'ar', '2025-12-27T10:20:22.245Z');
INSERT INTO lessons (id, user_id, student_name, student_email, student_phone, student_country_code, subject, custom_subject, duration, status, price, datetime, notes, language, created_at) VALUES ('LESSON-1766830822743', 1766757085889, 'Bashar Mawase', 'basharmawaseru@gmail.com', '0533618622', NULL, 'algebra', NULL, 60, 'new', 50, '2025-12-28T12:30', NULL, 'ar', '2025-12-27T10:20:22.743Z');
INSERT INTO lessons (id, user_id, student_name, student_email, student_phone, student_country_code, subject, custom_subject, duration, status, price, datetime, notes, language, created_at) VALUES ('LESSON-1766830823496', 1766757085889, 'Bashar Mawase', 'basharmawaseru@gmail.com', '0533618622', NULL, 'algebra', NULL, 60, 'new', 50, '2025-12-28T12:30', NULL, 'ar', '2025-12-27T10:20:23.496Z');
INSERT INTO lessons (id, user_id, student_name, student_email, student_phone, student_country_code, subject, custom_subject, duration, status, price, datetime, notes, language, created_at) VALUES ('LESSON-1766830826012', 1766757085889, 'Bashar Mawase', 'basharmawaseru@gmail.com', '0533618622', NULL, 'algebra', NULL, 60, 'new', 50, '2025-12-28T12:30', NULL, 'ar', '2025-12-27T10:20:26.012Z');
INSERT INTO lessons (id, user_id, student_name, student_email, student_phone, student_country_code, subject, custom_subject, duration, status, price, datetime, notes, language, created_at) VALUES ('LESSON-1766830828429', 1766757085889, 'Bashar Mawase', 'basharmawaseru@gmail.com', '0533618622', NULL, 'algebra', NULL, 60, 'new', 50, '2025-12-28T12:30', NULL, 'ar', '2025-12-27T10:20:28.429Z');
INSERT INTO lessons (id, user_id, student_name, student_email, student_phone, student_country_code, subject, custom_subject, duration, status, price, datetime, notes, language, created_at) VALUES ('LESSON-1766830829699', 1766757085889, 'Bashar Mawase', 'basharmawaseru@gmail.com', '0533618622', NULL, 'algebra', NULL, 60, 'new', 50, '2025-12-28T12:30', NULL, 'ar', '2025-12-27T10:20:29.699Z');
INSERT INTO lessons (id, user_id, student_name, student_email, student_phone, student_country_code, subject, custom_subject, duration, status, price, datetime, notes, language, created_at) VALUES ('LESSON-1766830830246', 1766757085889, 'Bashar Mawase', 'basharmawaseru@gmail.com', '0533618622', NULL, 'algebra', NULL, 60, 'new', 50, '2025-12-28T12:30', NULL, 'ar', '2025-12-27T10:20:30.246Z');
INSERT INTO lessons (id, user_id, student_name, student_email, student_phone, student_country_code, subject, custom_subject, duration, status, price, datetime, notes, language, created_at) VALUES ('LESSON-1766830830611', 1766757085889, 'Bashar Mawase', 'basharmawaseru@gmail.com', '0533618622', NULL, 'algebra', NULL, 60, 'new', 50, '2025-12-28T12:30', NULL, 'ar', '2025-12-27T10:20:30.611Z');
INSERT INTO lessons (id, user_id, student_name, student_email, student_phone, student_country_code, subject, custom_subject, duration, status, price, datetime, notes, language, created_at) VALUES ('LESSON-1766830940162', 1766830898147, 'Bashar', 'basharinimawasini@gmail.com', '0533618622', NULL, 'calculus', NULL, 120, 'new', 90, '2026-01-24T12:30', NULL, 'ru', '2025-12-27T10:22:20.162Z');
INSERT INTO lessons (id, user_id, student_name, student_email, student_phone, student_country_code, subject, custom_subject, duration, status, price, datetime, notes, language, created_at) VALUES ('LESSON-1766830940659', 1766830898147, 'Bashar', 'basharinimawasini@gmail.com', '0533618622', NULL, 'calculus', NULL, 120, 'new', 90, '2026-01-24T12:30', NULL, 'ru', '2025-12-27T10:22:20.659Z');
INSERT INTO lessons (id, user_id, student_name, student_email, student_phone, student_country_code, subject, custom_subject, duration, status, price, datetime, notes, language, created_at) VALUES ('LESSON-1766830941662', 1766830898147, 'Bashar', 'basharinimawasini@gmail.com', '0533618622', NULL, 'calculus', NULL, 120, 'new', 90, '2026-01-24T12:30', NULL, 'ru', '2025-12-27T10:22:21.662Z');
INSERT INTO lessons (id, user_id, student_name, student_email, student_phone, student_country_code, subject, custom_subject, duration, status, price, datetime, notes, language, created_at) VALUES ('LESSON-1766830941809', 1766830898147, 'Bashar', 'basharinimawasini@gmail.com', '0533618622', NULL, 'calculus', NULL, 120, 'new', 90, '2026-01-24T12:30', NULL, 'ru', '2025-12-27T10:22:21.809Z');
INSERT INTO lessons (id, user_id, student_name, student_email, student_phone, student_country_code, subject, custom_subject, duration, status, price, datetime, notes, language, created_at) VALUES ('LESSON-1766831051178', 1766830898147, 'Bashar', 'basharinimawasini@gmail.com', NULL, NULL, 'topology', NULL, 60, 'new', 50, '2026-03-21T12:23', NULL, 'ru', '2025-12-27T10:24:11.178Z');
INSERT INTO lessons (id, user_id, student_name, student_email, student_phone, student_country_code, subject, custom_subject, duration, status, price, datetime, notes, language, created_at) VALUES ('LESSON-1766831051677', 1766830898147, 'Bashar', 'basharinimawasini@gmail.com', NULL, NULL, 'topology', NULL, 60, 'new', 50, '2026-03-21T12:23', NULL, 'ru', '2025-12-27T10:24:11.677Z');
INSERT INTO lessons (id, user_id, student_name, student_email, student_phone, student_country_code, subject, custom_subject, duration, status, price, datetime, notes, language, created_at) VALUES ('LESSON-1766831052358', 1766830898147, 'Bashar', 'basharinimawasini@gmail.com', NULL, NULL, 'topology', NULL, 60, 'new', 50, '2026-03-21T12:23', NULL, 'ru', '2025-12-27T10:24:12.358Z');
INSERT INTO lessons (id, user_id, student_name, student_email, student_phone, student_country_code, subject, custom_subject, duration, status, price, datetime, notes, language, created_at) VALUES ('LESSON-1766834955376', 1766830898147, 'Bashar', 'basharinimawasini@gmail.com', '0533618622', '+972', 'calculus', NULL, 90, 'new', 0, 'undefined', NULL, 'en', '2025-12-27T11:29:15.376Z');
INSERT INTO lessons (id, user_id, student_name, student_email, student_phone, student_country_code, subject, custom_subject, duration, status, price, datetime, notes, language, created_at) VALUES ('LESSON-1766835285196', 1766830898147, 'Bashar', 'basharinimawasini@gmail.com', '0533618622', '+7', 'calculus', NULL, 60, 'new', 0, 'undefined', NULL, 'en', '2025-12-27T11:34:45.196Z');
INSERT INTO lessons (id, user_id, student_name, student_email, student_phone, student_country_code, subject, custom_subject, duration, status, price, datetime, notes, language, created_at) VALUES ('LESSON-1766835425156', 1766830898147, 'Bashar', 'basharinimawasini@gmail.com', '0533618622', '+972', 'geometry', NULL, 120, 'new', 0, 'undefined', NULL, 'he', '2025-12-27T11:37:05.156Z');

-- Courses
INSERT INTO courses (id, title_en, data) VALUES ('MTH-101', 'Calculus & Analysis', '{"id":"MTH-101","en":{"title":"Calculus & Analysis","description":"A rigorous introduction to limits, derivatives, integrals, and infinite series. This course builds the mathematical foundation required for advanced physics and engineering.","syllabus":["Limits and Continuity","Differentiation: Theory and Applications","Integration: Riemann Sums and Techniques","Sequences and Series","Introduction to Differential Equations"],"duration":"12 Weeks","level":"Foundational"},"ar":{"title":"التفاضل والتكامل والتحليل","description":"مقدمة دقيقة للنهايات، المشتقات، التكاملات، والمتسلسلات اللا نهائية. يبني هذا المساق الأساس الرياضي المطلوب للفيزياء والهندسة المتقدمة.","syllabus":["النهايات والاتصال","التفاضل: النظرية والتطبيقات","التكامل: مجاميع ريمان والتقنيات","المتتاليات والمتسلسلات","مقدمة في المعادلات التفاضلية"],"duration":"١٢ أسبوع","level":"تأسيسي"},"he":{"title":"חשבון אינפיניטסימלי","description":"מבוא קפדני לגבולות, נגזרות, אינטגרלים וטורים אינסופיים. קורס זה בונה את היסוד המתמטי הדרוש לפיזיקה מתקדמת והנדסה.","syllabus":["גבולות ורציפות","חשבון דיפרנציאלי: תיאוריה ויישומים","אינטגרלים: סכומי רימן ושיטות אינטגרציה","סדרות וטורים","מבוא למוואות דיפרנציאליות"],"duration":"12 שבועות","level":"יסודות"},"ru":{"title":"Математический Анализ","description":"Строгое введение в пределы, производные, интегралы и бесконечные ряды. Этот курс создает математическую базу, необходимую для передовой физики и инженерии.","syllabus":["Пределы и Непрерывность","Дифференцирование: Теория и Приложения","Интегрирование: Суммы Римана","Последовательности и Ряды","Введение в Дифференциальные Уравнения"],"duration":"12 Недель","level":"Базовый"},"videos":[]}');
INSERT INTO courses (id, title_en, data) VALUES ('MTH-102', 'Linear Algebra', '{"id":"MTH-102","en":{"title":"Linear Algebra","description":"Vector spaces, linear transformations, matrices, and eigenvalues. The language of quantum mechanics and machine learning.","syllabus":["Systems of Linear Equations","Vector Spaces and Subspaces","Linear Transformations","Determinants and Eigenvalues","Inner Product Spaces"],"duration":"10 Weeks","level":"Essential"},"ar":{"title":"الجبر الخطي","description":"الفضاءات المتجهية، التحويلات الخطية، المصفوفات، والقيم الذاتية. لغة ميكانيكا الكم والتعلم الآلي.","syllabus":["أنظمة المعادلات الخطية","الفضاءات المتجهية والفضاءات الجزئية","التحويلات الخطية","المحددات والقيم الذاتية","فضاءات الضرب الداخلي"],"duration":"١٠ أسابيع","level":"أساسي"},"he":{"title":"אלגברה ליניארית","description":"מרחבים וקטוריים, העתקות ליניאריות, מטריצות וערכים עצמיים. השפה של מכניקת הקוונטים ולמידת מכונה.","syllabus":["מערכות משוואות ליניאריות","מרחבים וקטוריים ותתי-מרחבים","העתקות ליניאריות","דטרמיננטות וערכים עצמיים","מרחבי מכפלה פנימית"],"duration":"10 שבועות","level":"חיוני"},"ru":{"title":"Линейная Алгебра","description":"Векторные пространства, линейные преобразования, матрицы и собственные значения. Язык квантовой механики и машинного обучения.","syllabus":["Системы Линейных Уравнений","Векторные Пространства","Линейные Преобразования","Определители и Собственные Значения","Пространства Внутреннего Произведения"],"duration":"10 Недель","level":"Важный"},"videos":[]}');
INSERT INTO courses (id, title_en, data) VALUES ('MTH-103', 'Discrete Mathematics', '{"id":"MTH-103","en":{"title":"Discrete Mathematics","description":"Logic, set theory, combinatorics, and graph theory. The mathematical structures behind computer science.","syllabus":["Propositional and Predicate Logic","Set Theory and Functions","Induction and Recursion","Graph Theory Basics","Combinatorics and Counting"],"duration":"10 Weeks","level":"Essential"},"ar":{"title":"الرياضيات المتقطعة","description":"المنطق، نظرية المجموعات، التوافيق، ونظرية البيان. الهياكل الرياضية وراء علوم الحاسوب.","syllabus":["المنطق الافتراضي والمسند","نظرية المجموعات والدوال","الاستقراء والتكرار","أساسيات نظرية البيان","التوافيق والعد"],"duration":"١٠ أسابيع","level":"أساسي"},"he":{"title":"מתמטיקה בדידה","description":"לוגיקה, תורת הקבוצות, קומבינטוריקה ותורת הגרפים. המבנים המתמטיים שמאחורי מדעי המחשב.","syllabus":["תחשיב הפסוקים והפרדיקטים","תורת הקבוצות ופונקציות","אינדוקציה ורקורסיה","יסודות תורת הגרפים","קומבינטוריקה וספירה"],"duration":"10 שבועות","level":"חיוני"},"ru":{"title":"Дискретная Математика","description":"Логика, теория множеств, комбинаторика и теория графов. Математические структуры информатики.","syllabus":["Логика Высказываний","Теория Множеств","Индукция и Рекурсия","Основы Теории Графов","Комбинаторика"],"duration":"10 Недель","level":"Важный"},"videos":[]}');
INSERT INTO courses (id, title_en, data) VALUES ('MTH-104', 'Probability Theory', '{"id":"MTH-104","en":{"title":"Probability Theory","description":"Quantifying uncertainty. Random variables, distributions, and limit theorems. The math of chance.","syllabus":["Probability Spaces and Axioms","Random Variables (Discrete & Continuous)","Expectation and Variance","Law of Large Numbers","Central Limit Theorem"],"duration":"12 Weeks","level":"Foundational"},"ar":{"title":"نظرية الاحتمالات","description":"قياس عدم اليقين. المتغيرات العشوائية، التوزيعات، ونظريات النهايات. رياضيات الصدفة.","syllabus":["فضاءات الاحتمال والبديهيات","المتغيرات العشوائية","التوقع والتباين","قانون الأعداد الكبيرة","نظرية النهاية المركزية"],"duration":"١٢ أسبوع","level":"تأسيسي"},"he":{"title":"תורת ההסתברות","description":"כימות אי-הודאות. משתנים מקריים, התפלגויות ומשפטי גבול. המתמטיקה של המקרה.","syllabus":["מרחבי הסתברות ואקסיומות","משתנים מקריים","תוחלת ושונות","חוק המספרים הגדולים","משפט הגבול המרכזי"],"duration":"12 שבועות","level":"יסודות"},"ru":{"title":"Теория Вероятностей","description":"Оценка неопределенности. Случайные величины, распределения и предельные теоремы. Математика шанса.","syllabus":["Вероятностные Пространства","Случайные Величины","Ожидание и Дисперсия","Закон Больших Чисел","Центральная Предельная Теорема"],"duration":"12 Недель","level":"Базовый"},"videos":[]}');
INSERT INTO courses (id, title_en, data) VALUES ('MTH-201', 'Abstract Algebra', '{"id":"MTH-201","en":{"title":"Abstract Algebra","description":"Groups, Rings, and Fields. Exploring the deep structures underlying arithmetic and symmetry.","syllabus":["Group Theory and Subgroups","Cyclic Groups and Permutations","Isomorphisms and Homomorphisms","Ring Theory Basics","Introduction to Fields"],"duration":"14 Weeks","level":"Advanced"},"ar":{"title":"الجبر المجرد","description":"الزمر، الحلقات، والحقول. استكشاف الهياكل العميقة الكامنة وراء الحساب والتناظر.","syllabus":["نظرية الزمر والزمر الجزئية","الزمر الدورية والتباديل","التشابه والتشاكل","أساسيات نظرية الحلقات","مقدمة في الحقول"],"duration":"١٤ أسبوع","level":"متقدم"},"he":{"title":"אלגברה מופשטת","description":"חבורות, חוגים ושדות. חקירת המבנים העמוקים העומדים בבסיס האריתמטיקה והסימטריה.","syllabus":["תורת החבורות","חבורות ציקליות ותמורות","איזומורפיזם והומומורפיזם","תורת החוגים","מבוא לשדות"],"duration":"14 שבועות","level":"מתקדם"},"ru":{"title":"Общая Алгебра","description":"Группы, кольца и поля. Изучение глубоких структур, лежащих в основе арифметики и симметрии.","syllabus":["Теория Групп","Циклические Группы","Изоморфизмы","Теория Колец","Введение в Поля"],"duration":"14 Недель","level":"Продвинутый"},"videos":[]}');
INSERT INTO courses (id, title_en, data) VALUES ('LANG-EN', 'Scientific English', '{"id":"LANG-EN","en":{"title":"Scientific English","level":"Intermediate","description":"Master the global language of science.","syllabus":[],"duration":"8 Weeks"},"ar":{"title":"اللغة الإنجليزية العلمية","level":"متوسط","description":"أتقن لغة العلم العالمية.","syllabus":[],"duration":"٨ أسابيع"},"he":{"title":"אנגלית מדעית","level":"בינוני","description":"שלטו בשפה הבינלאומית של המדע.","syllabus":[],"duration":"8 שבועות"},"ru":{"title":"Научный Английский","level":"Средний","description":"Овладейте глобальным языком науки.","syllabus":[],"duration":"8 Недель"},"videos":[]}');
INSERT INTO courses (id, title_en, data) VALUES ('LANG-AR', 'Modern Arabic', '{"id":"LANG-AR","en":{"title":"Modern Arabic","level":"Beginner","description":"Learn Modern Standard Arabic.","syllabus":[],"duration":"10 Weeks"},"ar":{"title":"اللغة العربية الفصحى","level":"متقدم","description":"دراسة متعمقة للنحو والصرف.","syllabus":[],"duration":"١٠ أسابيع"},"he":{"title":"ערבית ספרותית","level":"מתחילים","description":"למדו ערבית ספרותית מודרנית.","syllabus":[],"duration":"10 שבועות"},"ru":{"title":"Современный Арабский","level":"Начальный","description":"Изучайте современный арабский.","syllabus":[],"duration":"10 Недель"},"videos":[]}');
INSERT INTO courses (id, title_en, data) VALUES ('LANG-HE', 'Hebrew Language', '{"id":"LANG-HE","en":{"title":"Hebrew Language","level":"Beginner","description":"From Aleph-Bet to advanced reading.","syllabus":[],"duration":"10 Weeks"},"ar":{"title":"اللغة العبرية","level":"مبتدئ","description":"من الألف-ب إلى القراءة.","syllabus":[],"duration":"١٠ أسابيع"},"he":{"title":"עברית אקדמית","level":"מתקדם","description":"שיפור יכולות ההבעה.","syllabus":[],"duration":"10 שבועות"},"ru":{"title":"Иврит","level":"Начальный","description":"От Алеф-Бет до чтения.","syllabus":[],"duration":"10 Недель"},"videos":[]}');
INSERT INTO courses (id, title_en, data) VALUES ('LANG-RU', 'Russian Language', '{"id":"LANG-RU","en":{"title":"Russian Language","level":"Beginner","description":"Unlock Russian scientific literature.","syllabus":[],"duration":"12 Weeks"},"ar":{"title":"اللغة الروسية","level":"مبتدئ","description":"تعلم الروسية للأدب العلمي.","syllabus":[],"duration":"١٢ أسبوع"},"he":{"title":"השפה הרוסית","level":"מתחילים","description":"גישה לספרות הרוסית.","syllabus":[],"duration":"12 שבועות"},"ru":{"title":"Русский Язык","level":"Продвинутый","description":"Углубленное изучение.","syllabus":[],"duration":"12 Недель"},"videos":[]}');
INSERT INTO courses (id, title_en, data) VALUES ('LANG-PY', 'Python for Science', '{"id":"LANG-PY","en":{"title":"Python for Science","level":"Computational","description":"Data analysis and AI.","syllabus":[],"duration":"10 Weeks"},"ar":{"title":"بايثون للعلوم","level":"حاسوبي","description":"تحليل البيانات والذكاء الاصطناعي.","syllabus":[],"duration":"١٠ أسابيع"},"he":{"title":"פייתון למדעים","level":"חישובי","description":"ניתוח נתונים ו-AI.","syllabus":[],"duration":"10 שבועות"},"ru":{"title":"Python для Науки","level":"Вычислительный","description":"Анализ данных и ИИ.","syllabus":[],"duration":"10 Недель"},"videos":[]}');
